### ISSUE TITLE
Missing /modules directory

### ISSUE THREAD

**Issue by donburks** [prh1/avatar#1]
### Issue: 

Missing dependency to run application.

### Steps to repro:

- Check out repository to local
- `npm install`
- Add AWS Keys to configuration
- `node app.js`

### Desired behaviour

App runs.

### Actual behaviour

```
> node app.js

internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module './modules/scenarioHelper.js'
Require stack:
- /Users/don/dev/projects/avatar/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/don/dev/projects/avatar/app.js:13:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/don/dev/projects/avatar/app.js' ]
}
```

**Comment by prh1** [comment]
My mistake! I've added it now
